# Generated by Django 4.2.11 on 2025-05-22 10:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fin_products', '0002_savingsproduct_delete_depositcontract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savingsproduct',
            old_name='bank_name',
            new_name='kor_co_nm',
        ),
        migrations.AlterUniqueTogether(
            name='depositoption',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='savingsproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='savingsproduct',
            name='duration_months',
        ),
        migrations.RemoveField(
            model_name='savingsproduct',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='savingsproduct',
            name='monthly_limit',
        ),
        migrations.RemoveField(
            model_name='savingsproduct',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='savingsproduct',
            name='product_name',
        ),
        migrations.AddField(
            model_name='depositoption',
            name='intr_rate_type',
            field=models.CharField(default='단리', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='dcls_strt_day',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='fin_co_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='fin_co_subm_day',
            field=models.CharField(default=django.utils.timezone.now, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositproduct',
            name='mtrt_int',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='dcls_end_day',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='dcls_month',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='dcls_strt_day',
            field=models.CharField(default=django.utils.timezone.now, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='etc_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='fin_co_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='fin_co_subm_day',
            field=models.CharField(default=django.utils.timezone.now, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='fin_prdt_cd',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='fin_prdt_nm',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='join_deny',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='join_member',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='join_way',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='max_limit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='mtrt_int',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingsproduct',
            name='spcl_cnd',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='depositoption',
            name='save_trm',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='SavingsOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=10)),
                ('intr_rate_type_nm', models.CharField(max_length=20)),
                ('rsrv_type', models.CharField(max_length=10)),
                ('rsrv_type_nm', models.CharField(max_length=20)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('intr_rate2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='fin_products.savingsproduct')),
            ],
        ),
    ]
