# Generated by Django 4.2.11 on 2025-05-22 08:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SavingsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.IntegerField()),
                ('started_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('payment_date', models.DateField()),
                ('round_number', models.IntegerField()),
                ('total_round', models.IntegerField()),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_detail', to='Users.account')),
            ],
        ),
        migrations.CreateModel(
            name='DepositDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration_months', models.IntegerField()),
                ('started_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_detail', to='Users.account')),
            ],
        ),
    ]
